In [121]:
import pandas as pd
from numpy.random import randint

finaly=0
finali=0
finalj=0
finalk=0
finall=0
total=0
Tfinal=0
index=0

hotelCatogery=[12000,9000,6000,4000]
wed_Theame=[0,200,250,350,150]
H_accomadation=[450,0]
inOut=[0,450]
dayN=[0,500]
guest=[300,250,200]
df = pd.DataFrame(columns=['H_Grade','H_District','Guest_Sum', 'H_Accomadation', 'H_Type', 'W_DaN', 'W_Theme', 'Bugget'])

In [122]:
for x in hotelCatogery:
    total=x
    for y in guest:
        finaly=total
        finaly+=y
        
        for i in H_accomadation:
            finali=finaly
            finali+=i
            
            for j in inOut:
                finalj=finali
                finalj+=j
                
                for k in dayN:
                    finalk=finalj
                    finalk+=k
                    
                    for l in wed_Theame:
                        finall=finalk
                        finall+=l
                        print("  Grade  "+str(x)+"  guest "+str(y)+"  H_accomadation "+str(i)+"  InOut  "+str(j)+"  DayN  "+str(k)+"  wed_Theame  "+str(l)+"  budget  "+str(finall))
                        df.loc[index] = [str(x) ,str(6),str(y),str(i),str(j),str(k),str(l),str(finall)]
                        index+=1
                        finall=0
                finalk = 0
            
            finalj = 0
            
        finali = 0
        
    finaly=0

  Grade  12000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  0  budget  12750
  Grade  12000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  200  budget  12950
  Grade  12000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  250  budget  13000
  Grade  12000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  350  budget  13100
  Grade  12000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  150  budget  12900
  Grade  12000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  0  budget  13250
  Grade  12000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  200  budget  13450
  Grade  12000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  250  budget  13500
  Grade  12000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  350  budget  13600
  Grade  12000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  150  budget  13400
  Grade  12000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  0  budget  13200
  Grade  12000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  200  budget  13400
  Grade  12000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  250  budget  13450
  Grade  12000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  350  budget  13550
  Grade  12000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  150  budget  13350
  Grade  12000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  0  budget  13700
  Grade  12000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  200  budget  13900
  Grade  12000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  250  budget  13950
  Grade  12000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  350  budget  14050
  Grade  12000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  150  budget  13850
  Grade  12000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  0  budget  12300
  Grade  12000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  200  budget  12500
  Grade  12000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  250  budget  12550
  Grade  12000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  350  budget  12650
  Grade  12000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  150  budget  12450
  Grade  12000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  0  budget  12800
  Grade  12000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  200  budget  13000
  Grade  12000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  250  budget  13050
  Grade  12000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  350  budget  13150
  Grade  12000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  150  budget  12950
  Grade  12000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  0  budget  12750
  Grade  12000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  200  budget  12950
  Grade  12000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  250  budget  13000
  Grade  12000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  350  budget  13100
  Grade  12000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  150  budget  12900
  Grade  12000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  0  budget  13250
  Grade  12000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  200  budget  13450
  Grade  12000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  250  budget  13500
  Grade  12000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  350  budget  13600
  Grade  12000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  150  budget  13400
  Grade  12000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  0  budget  12700
  Grade  12000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  200  budget  12900
  Grade  12000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  250  budget  12950
  Grade  12000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  350  budget  13050
  Grade  12000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  150  budget  12850
  Grade  12000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  0  budget  13200
  Grade  12000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  200  budget  13400
  Grade  12000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  250  budget  13450
  Grade  12000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  350  budget  13550
  Grade  12000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  150  budget  13350
  Grade  12000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  0  budget  13150
  Grade  12000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  200  budget  13350
  Grade  12000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  250  budget  13400
  Grade  12000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  350  budget  13500
  Grade  12000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  150  budget  13300
  Grade  12000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  0  budget  13650
  Grade  12000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  200  budget  13850
  Grade  12000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  250  budget  13900
  Grade  12000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  350  budget  14000
  Grade  12000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  150  budget  13800
  Grade  12000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  0  budget  12250
  Grade  12000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  200  budget  12450
  Grade  12000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  250  budget  12500
  Grade  12000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  350  budget  12600
  Grade  12000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  150  budget  12400
  Grade  12000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  0  budget  12750
  Grade  12000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  200  budget  12950
  Grade  12000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  250  budget  13000
  Grade  12000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  350  budget  13100
  Grade  12000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  150  budget  12900
  Grade  12000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  0  budget  12700
  Grade  12000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  200  budget  12900
  Grade  12000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  250  budget  12950
  Grade  12000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  350  budget  13050
  Grade  12000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  150  budget  12850
  Grade  12000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  0  budget  13200
  Grade  12000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  200  budget  13400
  Grade  12000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  250  budget  13450
  Grade  12000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  350  budget  13550
  Grade  12000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  150  budget  13350
  Grade  12000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  0  budget  12650
  Grade  12000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  200  budget  12850
  Grade  12000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  250  budget  12900
  Grade  12000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  350  budget  13000
  Grade  12000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  150  budget  12800
  Grade  12000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  0  budget  13150
  Grade  12000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  200  budget  13350
  Grade  12000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  250  budget  13400
  Grade  12000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  350  budget  13500
  Grade  12000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  150  budget  13300
  Grade  12000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  0  budget  13100
  Grade  12000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  200  budget  13300
  Grade  12000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  250  budget  13350
  Grade  12000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  350  budget  13450
  Grade  12000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  150  budget  13250
  Grade  12000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  0  budget  13600
  Grade  12000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  200  budget  13800
  Grade  12000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  250  budget  13850
  Grade  12000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  350  budget  13950
  Grade  12000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  150  budget  13750
  Grade  12000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  0  budget  12200
  Grade  12000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  200  budget  12400
  Grade  12000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  250  budget  12450
  Grade  12000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  350  budget  12550
  Grade  12000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  150  budget  12350
  Grade  12000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  0  budget  12700
  Grade  12000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  200  budget  12900
  Grade  12000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  250  budget  12950
  Grade  12000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  350  budget  13050
  Grade  12000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  150  budget  12850
  Grade  12000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  0  budget  12650
  Grade  12000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  200  budget  12850
  Grade  12000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  250  budget  12900
  Grade  12000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  350  budget  13000
  Grade  12000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  150  budget  12800
  Grade  12000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  0  budget  13150

  Grade  12000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  200  budget  13350
  Grade  12000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  250  budget  13400
  Grade  12000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  350  budget  13500
  Grade  12000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  150  budget  13300
  Grade  9000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  0  budget  9750
  Grade  9000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  200  budget  9950
  Grade  9000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  250  budget  10000
  Grade  9000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  350  budget  10100
  Grade  9000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  150  budget  9900
  Grade  9000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  0  budget  10250
  Grade  9000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  200  budget  10450
  Grade  9000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  250  budget  10500
  Grade  9000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  350  budget  10600
  Grade  9000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  150  budget  10400
  Grade  9000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  0  budget  10200
  Grade  9000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  200  budget  10400
  Grade  9000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  250  budget  10450
  Grade  9000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  350  budget  10550
  Grade  9000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  150  budget  10350
  Grade  9000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  0  budget  10700
  Grade  9000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  200  budget  10900
  Grade  9000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  250  budget  10950
  Grade  9000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  350  budget  11050
  Grade  9000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  150  budget  10850
  Grade  9000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  0  budget  9300
  Grade  9000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  200  budget  9500
  Grade  9000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  250  budget  9550
  Grade  9000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  350  budget  9650
  Grade  9000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  150  budget  9450
  Grade  9000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  0  budget  9800
  Grade  9000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  200  budget  10000
  Grade  9000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  250  budget  10050
  Grade  9000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  350  budget  10150
  Grade  9000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  150  budget  9950
  Grade  9000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  0  budget  9750
  Grade  9000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  200  budget  9950
  Grade  9000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  250  budget  10000
  Grade  9000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  350  budget  10100
  Grade  9000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  150  budget  9900
  Grade  9000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  0  budget  10250
  Grade  9000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  200  budget  10450
  Grade  9000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  250  budget  10500
  Grade  9000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  350  budget  10600
  Grade  9000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  150  budget  10400
  Grade  9000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  0  budget  9700
  Grade  9000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  200  budget  9900
  Grade  9000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  250  budget  9950
  Grade  9000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  350  budget  10050
  Grade  9000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  150  budget  9850
  Grade  9000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  0  budget  10200
  Grade  9000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  200  budget  10400
  Grade  9000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  250  budget  10450
  Grade  9000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  350  budget  10550
  Grade  9000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  150  budget  10350
  Grade  9000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  0  budget  10150
  Grade  9000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  200  budget  10350
  Grade  9000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  250  budget  10400
  Grade  9000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  350  budget  10500
  Grade  9000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  150  budget  10300
  Grade  9000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  0  budget  10650
  Grade  9000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  200  budget  10850
  Grade  9000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  250  budget  10900
  Grade  9000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  350  budget  11000
  Grade  9000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  150  budget  10800
  Grade  9000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  0  budget  9250
  Grade  9000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  200  budget  9450
  Grade  9000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  250  budget  9500
  Grade  9000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  350  budget  9600
  Grade  9000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  150  budget  9400
  Grade  9000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  0  budget  9750
  Grade  9000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  200  budget  9950
  Grade  9000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  250  budget  10000
  Grade  9000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  350  budget  10100
  Grade  9000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  150  budget  9900
  Grade  9000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  0  budget  9700
  Grade  9000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  200  budget  9900
  Grade  9000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  250  budget  9950
  Grade  9000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  350  budget  10050
  Grade  9000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  150  budget  9850
  Grade  9000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  0  budget  10200
  Grade  9000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  200  budget  10400
  Grade  9000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  250  budget  10450
  Grade  9000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  350  budget  10550
  Grade  9000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  150  budget  10350
  Grade  9000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  0  budget  9650
  Grade  9000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  200  budget  9850
  Grade  9000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  250  budget  9900
  Grade  9000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  350  budget  10000
  Grade  9000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  150  budget  9800
  Grade  9000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  0  budget  10150
  Grade  9000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  200  budget  10350
  Grade  9000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  250  budget  10400
  Grade  9000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  350  budget  10500
  Grade  9000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  150  budget  10300
  Grade  9000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  0  budget  10100
  Grade  9000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  200  budget  10300
  Grade  9000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  250  budget  10350
  Grade  9000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  350  budget  10450
  Grade  9000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  150  budget  10250
  Grade  9000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  0  budget  10600
  Grade  9000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  200  budget  10800
  Grade  9000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  250  budget  10850
  Grade  9000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  350  budget  10950
  Grade  9000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  150  budget  10750
  Grade  9000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  0  budget  9200
  Grade  9000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  200  budget  9400
  Grade  9000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  250  budget  9450

  Grade  9000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  350  budget  9550
  Grade  9000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  150  budget  9350
  Grade  9000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  0  budget  9700
  Grade  9000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  200  budget  9900
  Grade  9000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  250  budget  9950
  Grade  9000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  350  budget  10050
  Grade  9000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  150  budget  9850
  Grade  9000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  0  budget  9650
  Grade  9000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  200  budget  9850
  Grade  9000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  250  budget  9900
  Grade  9000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  350  budget  10000
  Grade  9000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  150  budget  9800
  Grade  9000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  0  budget  10150
  Grade  9000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  200  budget  10350
  Grade  9000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  250  budget  10400
  Grade  9000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  350  budget  10500
  Grade  9000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  150  budget  10300
  Grade  6000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  0  budget  6750
  Grade  6000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  200  budget  6950
  Grade  6000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  250  budget  7000
  Grade  6000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  350  budget  7100
  Grade  6000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  150  budget  6900
  Grade  6000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  0  budget  7250
  Grade  6000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  200  budget  7450
  Grade  6000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  250  budget  7500
  Grade  6000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  350  budget  7600
  Grade  6000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  150  budget  7400
  Grade  6000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  0  budget  7200
  Grade  6000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  200  budget  7400
  Grade  6000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  250  budget  7450
  Grade  6000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  350  budget  7550
  Grade  6000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  150  budget  7350
  Grade  6000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  0  budget  7700
  Grade  6000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  200  budget  7900
  Grade  6000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  250  budget  7950
  Grade  6000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  350  budget  8050
  Grade  6000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  150  budget  7850
  Grade  6000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  0  budget  6300
  Grade  6000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  200  budget  6500
  Grade  6000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  250  budget  6550
  Grade  6000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  350  budget  6650
  Grade  6000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  150  budget  6450
  Grade  6000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  0  budget  6800
  Grade  6000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  200  budget  7000
  Grade  6000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  250  budget  7050
  Grade  6000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  350  budget  7150
  Grade  6000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  150  budget  6950
  Grade  6000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  0  budget  6750
  Grade  6000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  200  budget  6950
  Grade  6000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  250  budget  7000
  Grade  6000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  350  budget  7100
  Grade  6000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  150  budget  6900
  Grade  6000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  0  budget  7250
  Grade  6000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  200  budget  7450
  Grade  6000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  250  budget  7500
  Grade  6000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  350  budget  7600
  Grade  6000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  150  budget  7400
  Grade  6000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  0  budget  6700
  Grade  6000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  200  budget  6900
  Grade  6000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  250  budget  6950
  Grade  6000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  350  budget  7050
  Grade  6000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  150  budget  6850
  Grade  6000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  0  budget  7200
  Grade  6000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  200  budget  7400
  Grade  6000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  250  budget  7450
  Grade  6000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  350  budget  7550
  Grade  6000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  150  budget  7350
  Grade  6000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  0  budget  7150
  Grade  6000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  200  budget  7350
  Grade  6000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  250  budget  7400
  Grade  6000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  350  budget  7500
  Grade  6000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  150  budget  7300
  Grade  6000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  0  budget  7650
  Grade  6000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  200  budget  7850
  Grade  6000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  250  budget  7900
  Grade  6000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  350  budget  8000
  Grade  6000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  150  budget  7800
  Grade  6000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  0  budget  6250
  Grade  6000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  200  budget  6450
  Grade  6000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  250  budget  6500
  Grade  6000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  350  budget  6600
  Grade  6000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  150  budget  6400
  Grade  6000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  0  budget  6750
  Grade  6000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  200  budget  6950
  Grade  6000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  250  budget  7000
  Grade  6000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  350  budget  7100
  Grade  6000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  150  budget  6900
  Grade  6000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  0  budget  6700
  Grade  6000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  200  budget  6900
  Grade  6000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  250  budget  6950
  Grade  6000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  350  budget  7050
  Grade  6000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  150  budget  6850
  Grade  6000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  0  budget  7200
  Grade  6000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  200  budget  7400
  Grade  6000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  250  budget  7450
  Grade  6000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  350  budget  7550
  Grade  6000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  150  budget  7350
  Grade  6000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  0  budget  6650
  Grade  6000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  200  budget  6850
  Grade  6000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  250  budget  6900
  Grade  6000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  350  budget  7000

  Grade  6000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  150  budget  6800
  Grade  6000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  0  budget  7150
  Grade  6000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  200  budget  7350
  Grade  6000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  250  budget  7400
  Grade  6000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  350  budget  7500
  Grade  6000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  150  budget  7300
  Grade  6000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  0  budget  7100
  Grade  6000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  200  budget  7300
  Grade  6000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  250  budget  7350
  Grade  6000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  350  budget  7450
  Grade  6000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  150  budget  7250
  Grade  6000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  0  budget  7600
  Grade  6000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  200  budget  7800
  Grade  6000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  250  budget  7850
  Grade  6000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  350  budget  7950
  Grade  6000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  150  budget  7750
  Grade  6000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  0  budget  6200
  Grade  6000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  200  budget  6400
  Grade  6000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  250  budget  6450
  Grade  6000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  350  budget  6550
  Grade  6000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  150  budget  6350
  Grade  6000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  0  budget  6700
  Grade  6000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  200  budget  6900
  Grade  6000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  250  budget  6950
  Grade  6000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  350  budget  7050
  Grade  6000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  150  budget  6850
  Grade  6000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  0  budget  6650
  Grade  6000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  200  budget  6850
  Grade  6000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  250  budget  6900
  Grade  6000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  350  budget  7000
  Grade  6000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  150  budget  6800
  Grade  6000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  0  budget  7150
  Grade  6000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  200  budget  7350
  Grade  6000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  250  budget  7400
  Grade  6000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  350  budget  7500
  Grade  6000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  150  budget  7300
  Grade  4000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  0  budget  4750
  Grade  4000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  200  budget  4950
  Grade  4000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  250  budget  5000
  Grade  4000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  350  budget  5100
  Grade  4000  guest 300  H_accomadation 450  InOut  0  DayN  0  wed_Theame  150  budget  4900
  Grade  4000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  0  budget  5250
  Grade  4000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  200  budget  5450
  Grade  4000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  250  budget  5500
  Grade  4000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  350  budget  5600
  Grade  4000  guest 300  H_accomadation 450  InOut  0  DayN  500  wed_Theame  150  budget  5400
  Grade  4000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  0  budget  5200
  Grade  4000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  200  budget  5400
  Grade  4000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  250  budget  5450
  Grade  4000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  350  budget  5550
  Grade  4000  guest 300  H_accomadation 450  InOut  450  DayN  0  wed_Theame  150  budget  5350
  Grade  4000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  0  budget  5700
  Grade  4000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  200  budget  5900
  Grade  4000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  250  budget  5950
  Grade  4000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  350  budget  6050
  Grade  4000  guest 300  H_accomadation 450  InOut  450  DayN  500  wed_Theame  150  budget  5850
  Grade  4000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  0  budget  4300
  Grade  4000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  200  budget  4500
  Grade  4000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  250  budget  4550
  Grade  4000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  350  budget  4650
  Grade  4000  guest 300  H_accomadation 0  InOut  0  DayN  0  wed_Theame  150  budget  4450
  Grade  4000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  0  budget  4800
  Grade  4000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  200  budget  5000
  Grade  4000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  250  budget  5050
  Grade  4000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  350  budget  5150
  Grade  4000  guest 300  H_accomadation 0  InOut  0  DayN  500  wed_Theame  150  budget  4950
  Grade  4000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  0  budget  4750
  Grade  4000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  200  budget  4950
  Grade  4000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  250  budget  5000
  Grade  4000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  350  budget  5100
  Grade  4000  guest 300  H_accomadation 0  InOut  450  DayN  0  wed_Theame  150  budget  4900
  Grade  4000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  0  budget  5250
  Grade  4000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  200  budget  5450
  Grade  4000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  250  budget  5500
  Grade  4000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  350  budget  5600
  Grade  4000  guest 300  H_accomadation 0  InOut  450  DayN  500  wed_Theame  150  budget  5400
  Grade  4000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  0  budget  4700
  Grade  4000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  200  budget  4900
  Grade  4000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  250  budget  4950
  Grade  4000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  350  budget  5050
  Grade  4000  guest 250  H_accomadation 450  InOut  0  DayN  0  wed_Theame  150  budget  4850
  Grade  4000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  0  budget  5200
  Grade  4000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  200  budget  5400
  Grade  4000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  250  budget  5450
  Grade  4000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  350  budget  5550
  Grade  4000  guest 250  H_accomadation 450  InOut  0  DayN  500  wed_Theame  150  budget  5350
  Grade  4000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  0  budget  5150
  Grade  4000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  200  budget  5350
  Grade  4000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  250  budget  5400
  Grade  4000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  350  budget  5500
  Grade  4000  guest 250  H_accomadation 450  InOut  450  DayN  0  wed_Theame  150  budget  5300
  Grade  4000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  0  budget  5650
  Grade  4000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  200  budget  5850
  Grade  4000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  250  budget  5900
  Grade  4000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  350  budget  6000
  Grade  4000  guest 250  H_accomadation 450  InOut  450  DayN  500  wed_Theame  150  budget  5800
  Grade  4000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  0  budget  4250
  Grade  4000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  200  budget  4450
  Grade  4000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  250  budget  4500
  Grade  4000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  350  budget  4600
  Grade  4000  guest 250  H_accomadation 0  InOut  0  DayN  0  wed_Theame  150  budget  4400
  Grade  4000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  0  budget  4750
  Grade  4000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  200  budget  4950
  Grade  4000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  250  budget  5000

  Grade  4000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  350  budget  5100
  Grade  4000  guest 250  H_accomadation 0  InOut  0  DayN  500  wed_Theame  150  budget  4900
  Grade  4000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  0  budget  4700
  Grade  4000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  200  budget  4900
  Grade  4000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  250  budget  4950
  Grade  4000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  350  budget  5050
  Grade  4000  guest 250  H_accomadation 0  InOut  450  DayN  0  wed_Theame  150  budget  4850
  Grade  4000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  0  budget  5200
  Grade  4000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  200  budget  5400
  Grade  4000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  250  budget  5450
  Grade  4000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  350  budget  5550
  Grade  4000  guest 250  H_accomadation 0  InOut  450  DayN  500  wed_Theame  150  budget  5350
  Grade  4000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  0  budget  4650
  Grade  4000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  200  budget  4850
  Grade  4000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  250  budget  4900
  Grade  4000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  350  budget  5000
  Grade  4000  guest 200  H_accomadation 450  InOut  0  DayN  0  wed_Theame  150  budget  4800
  Grade  4000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  0  budget  5150
  Grade  4000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  200  budget  5350
  Grade  4000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  250  budget  5400
  Grade  4000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  350  budget  5500
  Grade  4000  guest 200  H_accomadation 450  InOut  0  DayN  500  wed_Theame  150  budget  5300
  Grade  4000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  0  budget  5100
  Grade  4000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  200  budget  5300
  Grade  4000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  250  budget  5350
  Grade  4000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  350  budget  5450
  Grade  4000  guest 200  H_accomadation 450  InOut  450  DayN  0  wed_Theame  150  budget  5250
  Grade  4000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  0  budget  5600
  Grade  4000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  200  budget  5800
  Grade  4000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  250  budget  5850
  Grade  4000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  350  budget  5950
  Grade  4000  guest 200  H_accomadation 450  InOut  450  DayN  500  wed_Theame  150  budget  5750
  Grade  4000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  0  budget  4200
  Grade  4000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  200  budget  4400
  Grade  4000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  250  budget  4450
  Grade  4000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  350  budget  4550
  Grade  4000  guest 200  H_accomadation 0  InOut  0  DayN  0  wed_Theame  150  budget  4350
  Grade  4000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  0  budget  4700
  Grade  4000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  200  budget  4900
  Grade  4000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  250  budget  4950
  Grade  4000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  350  budget  5050
  Grade  4000  guest 200  H_accomadation 0  InOut  0  DayN  500  wed_Theame  150  budget  4850
  Grade  4000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  0  budget  4650
  Grade  4000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  200  budget  4850
  Grade  4000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  250  budget  4900
  Grade  4000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  350  budget  5000
  Grade  4000  guest 200  H_accomadation 0  InOut  450  DayN  0  wed_Theame  150  budget  4800
  Grade  4000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  0  budget  5150
  Grade  4000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  200  budget  5350
  Grade  4000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  250  budget  5400
  Grade  4000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  350  budget  5500
  Grade  4000  guest 200  H_accomadation 0  InOut  450  DayN  500  wed_Theame  150  budget  5300

In [123]:
print(index)

480

In [124]:
df["H_Grade"].replace({"12000": "5", "9000": "4", "6000": "3", "4000": "2"}, inplace=True)
df["Guest_Sum"].replace({"300": "1", "250": "2", "200": "3"}, inplace=True)
df["H_Accomadation"].replace({"450": "1"}, inplace=True)
df["H_Type"].replace({"450": "1"}, inplace=True)
df["W_DaN"].replace({"500": "1"}, inplace=True)
df["W_Theme"].replace({"200": "1", "250": "2", "350": "3", "150": "4"}, inplace=True)
df.to_csv(r'outputKandy.csv', index=False)